services:
  nginx:
    image: fastapi-template.nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - python
  python:
    image: fastapi-template.python
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      SQLALCHEMY_DATABASE_URL: $SQLALCHEMY_DATABASE_URL
    ports:
      - 8000:8000
  migrate:
    image: fastapi-template.migrate
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      SQLALCHEMY_DATABASE_URL: $SQLALCHEMY_DATABASE_URL
  postgres:
    image: fastapi-template.postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
  mysql:
    image: fastapi-template.mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
