FROM python:3.12-slim-bookworm AS base
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
FROM base AS builder
COPY requirements.txt .
RUN pip install --no-dependencies --no-cache-dir -r requirements.txt

# Copy the source code
FROM base
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin/uvicorn /usr/local/bin/uvicorn
COPY . .
CMD ["python", "main.py"]
